version: 2

sources:
  - name: northwind
    schema: main
    tables:
      - name: customers
        description: "Contains customer details."
        columns:
          - name: customerid
            description: "Unique identifier for each customer."
            tests:
              - not_null
              - unique
      - name: orders        
        description: "Contains basic info about each order."
        columns:
          - name: orderid
            description: "Unique identifier for each order."
            tests:
              - not_null
              - unique
      - name: "order_details" #alias for cleaner references within dbt
        description: "Contains details about what products are in each order."
        identifier: "Order Details" # Actual table name in the database
        tests:
          - dbt_utils.unique_combination_of_columns:
              combination_of_columns:
                - orderid
                - productid
      - name: products
        description: "Contains info on each product offered."
        columns:
          - name: productid
            description: "Unique identifier for each product."
            tests:
              - not_null
              - unique
      - name: employees
        description: "Contains info on each employee."
        columns:
          - name: employeeid
            description: "Unique identifier for each employee."
            tests:
              - not_null
              - unique
      - name: shippers
        description: "Contains info on each shipping company used."
        columns:
          - name: shipperid
            description: "Unique identifier for each shipper."
            tests:
              - not_null
              - unique

models:
  - name: employee_sales_performance
    description: "Analyzes employee sales performance by year, including total sales and rankings."
    tests:
       - dbt_utils.unique_combination_of_columns:
           combination_of_columns:
             - employeeid
             - sales_year
    columns:
      - name: employeeid
        description: "Unique identifier for each employee."
      - name: sales_year
        description: "The year of the sales data."
      - name: total_sales
        description: "The total sales value for the employee in the given year."
      - name: yearly_rank
        description: "The rank of the employee based on total sales for the given year."

  - name: inventory_restocking
    description: "Generates a restocking report based on inventory levels and average daily sales."
    columns:
      - name: productid
        description: "Unique identifier for the product."
        tests:
          - not_null
      - name: unitsinstock
        description: "The current number of units available in stock."
      - name: reorder_quantity
        description: "The quantity to reorder if stock falls below the reorder level."

  - name: order_fulfillment_times
    description: "Analyzes the time taken to fulfill orders and flags outliers."
    columns:
      - name: orderid
        description: "Unique identifier for the order."
        tests:
          - not_null
      - name: fulfillment_days
        description: "The number of days it took to fulfill the order."
      - name: fulfillment_flag
        description: "Indicates whether the order is an outlier based on fulfillment time."

  - name: sales_analysis_by_customer
    description: "Summarizes total sales and order behavior by customer."
    columns:
      - name: customerid
        description: "Unique identifier for each customer."
        tests:
          - not_null
      - name: total_orders
        description: "Total number of orders placed by the customer."
      - name: total_sales
        description: "Total amount spent by the customer."
      - name: avg_order_value
        description: "The average value of the customer's orders."
      - name: last_order_date
        description: "Date of the most recent order placed by the customer."

  - name: sales_summary
    description: "Summarizes total sales per order, including discounts."
    columns:
      - name: orderid
        description: "Unique identifier for each order."
        tests:
          - not_null
      - name: customerid
        description: "Unique identifier for the customer."
      - name: total_order_value
        description: "Total value of the order after discounts."

  - name: product_performance
    description: "Analyzes product sales, revenue, and stock levels."
    columns:
      - name: productid
        description: "Unique identifier for each product."
        tests:
          - not_null
      - name: total_quantity_sold
        description: "Total quantity sold for the product."
      - name: total_revenue
        description: "Total revenue generated from the product."

  - name: cheapest_shipper_by_region
    description: "Finds the cheapest shipping company per region for single-product orders."
    tests:
       - dbt_utils.unique_combination_of_columns:
           combination_of_columns:
             - productid
             - freight_company
             - shipregion
    columns:
      - name: productid
        description: "Unique identifier for each product."
        tests:
          - not_null
      - name: freight_company
        description: "Name of the shipping company."
      - name: shipregion
        description: "Geographic region the order is shipped to."
      - name: avg_freight_per_unit
        description: "Average freight cost per unit for the product in the region."
      - name: cheapest_shipper_for_region
        description: "Indicates the cheapest shipping company for this product in the region."
      - name: total_orders
        description: "Total number of single-product orders analyzed for this shipper."

  - name: price_variation
    description: "Tracks net price variations per product over time, including total quantity sold at each price point."
    columns:
      - name: order_year
        description: "Year of the order."
      - name: productid
        description: "Unique identifier for each product."
        tests:
          - not_null
      - name: productname
        description: "Name of the product."
      - name: net_price
        description: "Final product price after discount."
      - name: total_quantity_sold
        description: "Total quantity sold at this net price."
      - name: total_orders
        description: "Number of orders that included this product at this price."

