dbt_northwind:
  outputs:
    dev:
      type: sqlite
      threads: 1
      database: 'database'
      schema: 'main'
      schemas_and_paths:
        main: "data/northwind.db"
      schema_directory: "data"

    prod:
      type: sqlite
      threads: 1
      database: 'database'
      schema: 'main'
      schemas_and_paths:
        main: "data/prod_northwind.db"
      schema_directory: "data"

  target: dev

